# H2 In-Memory Database Configuration
spring.datasource.url=jdbc:h2:mem:jaipur_db;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=Assignment56@
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Gemini API Key
gemini.api.key=AIzaSyDiyGWNVuh_mVGKxV294R3c3TK4c8HrPq0